/*
 * Copyright 2010-2015 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.kotlin.js.test.semantics;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.JetTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("js/js.translator/testData/inlineOperators/cases")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class InlineOperatorsJsTestGenerated extends AbstractInlineOperatorsJsTest {
    public void testAllFilesPresentInCases() throws Exception {
        JetTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("js/js.translator/testData/inlineOperators/cases"), Pattern.compile("^(.+)\\.kt$"), true);
    }

    @TestMetadata("div.kt")
    public void testDiv() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/div.kt");
        doTest(fileName);
    }

    @TestMetadata("get.kt")
    public void testGet() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/get.kt");
        doTest(fileName);
    }

    @TestMetadata("in.kt")
    public void testIn() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/in.kt");
        doTest(fileName);
    }

    @TestMetadata("minus.kt")
    public void testMinus() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/minus.kt");
        doTest(fileName);
    }

    @TestMetadata("mod.kt")
    public void testMod() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/mod.kt");
        doTest(fileName);
    }

    @TestMetadata("plus.kt")
    public void testPlus() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/plus.kt");
        doTest(fileName);
    }

    @TestMetadata("rangeTo.kt")
    public void testRangeTo() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/rangeTo.kt");
        doTest(fileName);
    }

    @TestMetadata("set.kt")
    public void testSet() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/set.kt");
        doTest(fileName);
    }

    @TestMetadata("times.kt")
    public void testTimes() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/times.kt");
        doTest(fileName);
    }

    @TestMetadata("unaryMinus.kt")
    public void testUnaryMinus() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/unaryMinus.kt");
        doTest(fileName);
    }

    @TestMetadata("unaryPlus.kt")
    public void testUnaryPlus() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("js/js.translator/testData/inlineOperators/cases/unaryPlus.kt");
        doTest(fileName);
    }
}
