// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
package org.jetbrains.kotlin.gradle.dsl

interface KotlinJsOptions  : org.jetbrains.kotlin.gradle.dsl.KotlinCommonOptions {

    /**
     * Whether a main function should be called
     * Possible values: "call", "noCall"
     * Default value: "call"
     */
    @get:org.gradle.api.tasks.Input
     var main: kotlin.String

    /**
     * Generate .meta.js and .kjsm files with metadata. Use to create a library
     * Default value: true
     */
    @get:org.gradle.api.tasks.Input
     var metaInfo: kotlin.Boolean

    /**
     * Kind of a module generated by compiler
     * Possible values: "plain", "amd", "commonjs", "umd"
     * Default value: "plain"
     */
    @get:org.gradle.api.tasks.Input
     var moduleKind: kotlin.String

    /**
     * Don't use bundled Kotlin stdlib
     * Default value: true
     */
    @get:org.gradle.api.tasks.Input
     var noStdlib: kotlin.Boolean

    /**
     * Output file path
     * Default value: null
     */
    @get:org.gradle.api.tasks.Optional
    @get:org.gradle.api.tasks.Input
     var outputFile: kotlin.String?

    /**
     * Generate source map
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
     var sourceMap: kotlin.Boolean

    /**
     * Generate JS files for specific ECMA version
     * Possible values: "v5"
     * Default value: "v5"
     */
    @get:org.gradle.api.tasks.Input
     var target: kotlin.String

    /**
     * Translate primitive arrays to JS typed arrays
     * Default value: false
     */
     var typedArrays: kotlin.Boolean
}