// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
package org.jetbrains.kotlin.gradle.dsl

interface KotlinCommonOptions {

    /**
     * Allow to use declarations only from the specified version of bundled libraries
     * Possible values: "1.0", "1.1"
     * Default value: "1.1"
     */
    @get:org.gradle.api.tasks.Input
     var apiVersion: kotlin.String

    /**
     * Provide source compatibility with specified language version
     * Possible values: "1.0", "1.1"
     * Default value: "1.1"
     */
    @get:org.gradle.api.tasks.Input
     var languageVersion: kotlin.String

    /**
     * Generate no warnings
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
     var suppressWarnings: kotlin.Boolean

    /**
     * Enable verbose logging output
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
     var verbose: kotlin.Boolean

    /**
     * A list of additional compiler arguments
     * Default value: emptyList()
     */
     var freeCompilerArgs: kotlin.collections.List<kotlin.String>
}
